// Music zones through the real rig (IWER). Uses music.force for the fight/after phases so the score can be checked
// without the bear AI cooperating. Woods and cave are driven by position alone.
import fs from 'fs'; import { boot } from './boot.mjs';
const [dist, outPath] = process.argv.slice(2);
const { ev, close } = await boot(dist);
for (const f of ['pagelib.js']) await ev(fs.readFileSync(new URL('./' + f, import.meta.url), 'utf8'));
const m = () => ev(() => T.x(() => __house.state().music));
const secs = (s) => ev((n) => T.frames(n), Math.round(s * 72));
const out = { checks: {} };
await ev(() => T.x(() => __house.chopDoor()));
out.start = await m();
const den = await ev(() => T.x(() => { const b = __house.world.bear; const d = b.den(); return [d.x, b.root.position.y, d.z]; }));
await ev((d) => T.x(() => __house.place(d[0] - 2.5, d[1] + 0.6, d[2])), den);
out.w0 = await m(); await secs(1); out.w1 = await m(); await secs(6);
out.woods = await m(); console.log(JSON.stringify([out.w0, out.w1]));
out.checks.woodsFadeIn = out.woods?.mode === 'woods' && out.woods.woods > 0.2;
await ev(() => T.x(() => __house.forceMusic('wake')));
await secs(2);
out.wake = await m();
out.checks.wakeRises = out.wake?.mode === 'wake' && out.wake.woods > out.woods.woods + 0.08;
await ev(() => T.x(() => __house.forceMusic('fight')));
await secs(4);
out.fight = await m();
out.checks.fightSwells = out.fight?.mode === 'fight' && out.fight.fight > 0.55;
await ev(() => T.x(() => { __house.forceMusic('after'); const b = __house.world.bear; b._s.state = 'dead'; b._s.t = 0; }));
await secs(12);
out.after = await m();
out.checks.fadesOutAfter = out.after?.fight < 0.12 && out.after.woods < 0.12;
await ev(() => T.x(() => { const c = __house.world.cave; const r = c.room; __house.place((r.x0 + r.x1) / 2, c.floor, (r.z0 + r.z1) / 2); }));
await secs(7);
out.cave = await m();
out.checks.caveBed = out.cave?.mode === 'cave' && out.cave.cave > 0.12 && out.cave.cave < 0.3;
await ev(() => T.x(() => __house.place(1.5, 0, 6)));
await secs(10);
out.yard = await m();
out.checks.silentInYard = out.yard?.mode === 'off' && out.yard.cave < 0.06 && out.yard.woods < 0.06 && out.yard.fight < 0.06;
fs.writeFileSync(outPath, JSON.stringify(out, null, 1));
const bad = Object.entries(out.checks).filter(([, v]) => !v);
console.log(Object.entries(out.checks).map(([k, v]) => `${v ? 'PASS' : 'FAIL'} ${k}`).join('\n'));
console.log(JSON.stringify({ woods: out.woods, wake: out.wake, fight: out.fight, after: out.after, cave: out.cave, yard: out.yard }));
await close(); process.exit(bad.length ? 1 : 0);
